### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by voidlynx** [botigram/lists#1]
### Bot Name

YUNG HEFNER

### Description

ну типа эм слышали трек моргена ён хефнер? смешной очень.

### Message Link

https://t.me/OAOAOMMM

### Channel link

https://t.me/OAOAOMMM

### Bot avatar URL

https://pyt.igorek.dev/images/morgen.png

### Bot source code URL

https://www.youtube.com/channel/UCWnqnojAgMdN0fQpr_xByJw

### Add Tags

моргенштерн, срать, смешно, хохлы, харош

**Comment by arslee07** [comment]
эм

**Comment by voidlynx** [comment]
мрогенщтен

**Comment by voidlynx** [comment]
я жду

**Comment by voidlynx** [comment]
ей ей юн хефнер

**Comment by arslee07** [comment]
й

пн, 13 дек. 2021 г., 16:17 Calamity ***@***.***>:

**Comment by arslee07** [comment]
![IMG_20220103_224602_667](https://user-images.githubusercontent.com/50916030/147937744-18197c38-6f83-4b51-9fda-b3dc9edf929c.jpg)

**Comment by voidlynx** [comment]
ну я
